name: site-security-scan
on:
  schedule:
    # Runs every Monday At 01:00.
    # - cron:  '0 1 * * 1'

    # Initial Test runs at minute one on the hour
    - cron: "1 * * * *"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the platform services registry
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          # Target URL
          target: "https://registry-web-platform-registry-dev.apps.silver.devops.gov.bc.ca"
          # The Docker file to be executed (optional)
          docker_name: "owasp/zap2docker-stable"
          # Relative path of the ZAP configuration file (optional)
          # rules_file_name: '.zap/rules.tsv'
          # Additional command line options (optional)
          # cmd_options: '-a'
